services:
    db:
        image: postgres:15
        container_name: voucher_db
        environment:
            POSTGRES_DB: voucher_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin1234
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: on-failure

    app:
        build:
            context: ./voucher.management
            dockerfile: Dockerfile
        container_name: voucher_app
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/voucher_db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: admin1234
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SPRING_JPA_SHOW_SQL: "true"
            SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
            
        restart: on-failure

volumes:
    pgdata:
